#!/bin/bash

source ~/.local/etc/bash/sys.bash

function source_maybe () {
  if [ -r "$1" ] ; then
      source "$1"
  fi
}

source_maybe ~/.local/etc/bash/path.$SYSOSTYPE

# If not running interactively, don't do anything.
[ -z "$PS1" ] && return

source_maybe ~/.local/etc/bash/term.bash
source_maybe ~/.local/etc/bash/term.$SYSOSTYPE
source_maybe ~/.local/etc/bash/generic.clj.bash
source_maybe ~/.local/etc/bash/alias.bash

export PROMPT_COMMAND="prompt-update"
prepare-for-prompt-update-ps1
function prompt-update () {
  history -a
  prompt-update-ps1
}

source_maybe ~/.local/etc/bash/site-local.bash
source_maybe ~/.local/etc/bash/host-local.bash
