#!/bin/bash

# On linux: "linux", on Mac OS X: "darwin".
UNAME="$(uname)"
case "$UNAME" in
  Linux) UNAME=linux ;;
  Darwin) UNAME=darwin ;;
esac

# TODO: Add a compilation function (to pool.manage) that recreates .bashrc
# from all these sources.  The corresponding .book line could look like:
# build "clj/project.clj" to "~/.local/share/java/project.clj"
function source_maybe () {
  local filename="$1"
  local name="$2"
  local was_sourced="__bash_sourced_$name"
  if [ -z "${!was_sourced}" -a -r "$filename" ] ; then
      source "$filename"
      # If name starts with a capital letter, also prevent reloading in
      # subshells.
      if [[ "${name:0:1}" =~ [A-Z] ]] ; then
          export "${was_sourced}"=t
      else
        let "${was_sourced}"=t
      fi
  fi
}
export -f source_maybe

source_maybe ~/.local/lib/bash/path.$UNAME Path_UNAME

# If not running interactively, don't do anything.
[ -z "$PS1" ] && return

PROMPT_COMMAND="prompt_update"
function prompt_update () {
  history -a
}

source_maybe ~/.local/lib/bash/term.bash term_bash
source_maybe ~/.local/lib/bash/term.$UNAME term_UNAME
source_maybe ~/.local/lib/bash/generic.clj.bash generic_clj
source_maybe ~/.local/lib/bash/alias.bash alias_bash
source_maybe ~/.local/lib/bash/alias.$UNAME alias_UNAME
source_maybe ~/.local/lib/bash/util.bash util_bash

prompt_update_init

source_maybe ~/.local/lib/bash/site-local.bash site_local_bash
source_maybe ~/.local/lib/bash/host-local.bash host_local_bash
