#!/bin/sh

source "$HOME/.zshenv" 2>/dev/null
emacs --daemon &

# Reverse the direction of mouse wheel.
xinput list | grep -v 'XTEST' |
    sed -e \
        '/slave *pointer/b useful;
         d; # Delete anything else.
         :useful s/[⎜↳ ]*\(.*\) *id=\([0-9]*\).*/\2 \1/g' | \
    while read id name
    do
      printf "[id: %02d] %s\n" "$id" "$name"
      xinput set-prop "$id" 'libinput Natural Scrolling Enabled' 1
      xinput set-prop "$id" 'libinput Accel Speed' 0.6
    done

# According to some documentaions when /etc/default/keyboard is properly
# configured[1], the following setxkbmap line should be redundant.  However,
# in my current setup Xserver does not honour /etc/default/keyboard.
# [1]: Currently I have the following lines in /etc/default/keyboard:
#   XKBMODEL="pc105"
#   XKBLAYOUT="us"
#   XKBVARIANT=""
#   XKBOPTIONS="ctrl:nocaps,altwin:swap_alt_win"
#   BACKSPACE="guess"
setxkbmap -option 'ctrl:nocaps,altwin:swap_alt_win'

# unset LC_ALL
# export LANG=en_US.UTF-8
# export LC_MESSAGES=C
# export LC_TIME=en_US.UTF-8
# export AWT_TOOLKIT=XToolkit
# xsetroot -solid "#222"
# xset -dpms
# xset s off
# xset -b
