#!/bin/sh

# zshenv: all types
# zprofile, zlogin, zlogout: login shells
# zshrc: interactive shells
# The order is: zshenv, zprofile, zshrc, zlogin, run, zlogout

# On linux: "linux", on Mac OS X: "darwin".
if [[ -z "$UNAME" ]] ; then
    case "$(uname)" in
      Linux) export UNAME=linux ;;
      Darwin) export UNAME=darwin ;;
    esac
fi

export PATH="$HOME/.local/bin/$UNAME:$HOME/.local/bin:$HOME/.opt/bin:$PATH"
export GOPATH="$HOME/.local"

source "$HOME/Pool/site/etc/zshenv" 2>/dev/null
source "$HOME/Pool/host/etc/zshenv" 2>/dev/null
