#!/bin/zsh

# zshenv: all types
# zprofile, zlogin, zlogout: login shells
# zshrc: interactive shells
# The order is: zshenv, zprofile, zshrc, zlogin, run, zlogout

# On linux: "linux", on Mac OS X: "darwin".
UNAME="$(uname)"
case "$UNAME" in
  Linux) UNAME=linux ;;
  Darwin) UNAME=darwin ;;
esac

export PATH="$HOME/.local/bin/$UNAME:$HOME/.local/bin:$HOME/.opt/bin:$PATH"
export GOPATH="$HOME/.local"

source "$HOME/Pool/site/etc/zshenv" 2>/dev/null
source "$HOME/Pool/host/etc/zshenv" 2>/dev/null
