#!/usr/bin/python -i
# -*- coding: utf-8 -*-

import os, shutil, sys
import re
import rlcompleter, readline, atexit

historyPath = os.path.expanduser("~/.history/python")
if os.uname()[0] == 'Darwin':
    readline.parse_and_bind('bind ^I rl_complete')
else:
    readline.parse_and_bind('tab: complete')

if os.path.exists(historyPath):
    readline.read_history_file(historyPath)

def save_history(historyPath=historyPath):
    readline.write_history_file(historyPath)

atexit.register(save_history)
